Traceback (most recent call last):
  File "tests/Python_Errors/AssertionError.py", line 3, in <module>
    assertSom("as")
  File "tests/Python_Errors/AssertionError.py", line 2, in assertSom
    assert (some==""), "Somefing"
AssertionError: Somefing
